# Generated by Django 4.1.7 on 2023-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('name', 'total_amount')},
        ),
    ]
