# Generated by Django 4.1.7 on 2023-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0002_income_name_alter_income_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
    ]
